version: '3.1'

services:

  #service name
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'app_matomo'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456789'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456789'
    
  #service name
  app_matomo:
    image: matomo:3.8.1
    restart: always
    links:
      - db
    ports:
      - "4000:80" 
    volumes:
      - "/home/huioqy/Code_Library/matomo_config:/var/www/html/config:rw"
      - "/home/huioqy/Code_Library/matomo_logs:/var/www/html/logs"

  #service name
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8082

  #service name
  webserver:
    image: 'bitnami/apache:latest'
    ports:
      - 8080:8080
    volumes:
      - /home/huioqy/NTU/Docker_Matomo_MySQL_local/website/:/app


