version: '3.1'

services:

  #service name
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456789'
    
  #service name
  app_matomo:
    image: matomo:3.8.1
    restart: always
    links:
      - db
    ports:
      - "4000:80" 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
