# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'app_matomo'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456789'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456789'
    volumes:
      # maps the local directory inside the container where MySQL stores all of its data by default.
      - "/home/huioqy/Code_Library/mysql_db_volumes:/var/lib/mysql"
    
  #service name
  app_matomo:
    image: matomo:3.8.1
    restart: always
    links:
      - db
    ports:
      - "4000:80"  #http://0.0.0.0/index.php
    volumes:
      - "/home/huioqy/Code_Library/matomo_config:/var/www/html/config:rw"
      - "/home/huioqy/Code_Library/matomo_logs:/var/www/html/logs"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
